GET http://localhost:8080/setor
###
POST http://localhost:8080/setor HTTP/1.1
content-type: application/json

{        
    "nome" : "Teste"
}
###
PUT  http://localhost:8080/setor/657 HTTP/1.1
content-type: application/json

{
    "nome" : "Teste Update"
}
###
DELETE  http://localhost:8080/setor/655
