version: "3.5"
services:
  db:
    image: mysql:8
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE: db_corretora
    ports:
      - 3306:3306
  backend:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - ROOT_USER: root
      - ROOT_PASSWORD: root